version: "3.8"

services:
  ray-head:
    image: camazaqui/ray-horovod:latest
    ports:
      - "6379:6379"
      - "8265:8265"
      - "10001:10001"
    command: bash -c "ray start --head --dashboard-port=8265 --port=6379 --dashboard-host=0.0.0.0 --redis-password=passwd --block"
    shm_size: 2g
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    networks:
      - ray_net
  ray-worker:
    image: camazaqui/ray-horovod:latest
    ports:
      - "9500:9500"
    depends_on:
      - ray-head
    command: bash -c "ray start --address=ray-head:6379 --redis-password=passwd --num-cpus=2 --block"
    shm_size: 2g
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role==worker"
      resources:
        limits:
          cpus: '2'
          memory: '2g'
    networks:
      - ray_net

networks:
  ray_net: